### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by ShootingStarr** [csscomb/sublime-csscomb#11]
Зачем в настройках по умолчанию происходит такой ад?

Есть у меня стили для селектора:

``` css
.block {
  display: block;
  padding-top: 13px;
  padding-bottom: 13px;
  padding-left: 11px;
  background: red;
  color: #706f6f;
  text-decoration: none;
  font-style: normal;
  font-size: 13px;
  line-height: 1;
  &:hover {
    color: #f39000;
  }
}
```

После сортировки он выглядит вот так:

``` css
.block
{
    font-size: 13px;
    font-style: normal;
    line-height: 1;

    display: block;

    padding-top: 13px;
    padding-bottom: 13px;
    padding-left: 11px;

    text-decoration: none;

    color: #706f6f;
    background: red;
  &:hover
{
    color: #f39000;
}
}

```

Зачем по умолчанию менять позицию скобок?
