### ISSUE TITLE
Sorting attributes removes indentation and adds linebreak 

### ISSUE THREAD

**Issue by Jarrydcrawford** [csscomb/sublime-csscomb#21]
I've recently restarted my computer and I'm assuming that CSScomb was updated along with restarting ST3. Sorting my SCSS results in weird behaviour where selecting the attributes I want to sort (either by mouse or <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd>), and then sorting the attributes (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>) below the first line loses indentation, and a new line is added to the end. Looks like it's not sorting either. Trying to sort vanilla CSS in the same method results in an error.

Package:
![csscomb-list](https://cloud.githubusercontent.com/assets/3292452/3669038/54300e9a-122b-11e4-8bb4-de7df342da83.png)

Original:

``` scss
#featured-blog {
    .blog-title {
        margin: 0;
        line-height: 1;
        font-size: 40px;
        color: $brand-primary;
    }
    ...
}
```

Pre-update:

``` scss
#featured-blog {
    .blog-title {
        margin: 0;
        color: $brand-primary;
        font-size: 40px;
        line-height: 1;
    }
    ...
}
```

Post-update:

``` scss
#featured-blog {
    .blog-title {
        margin: 0;
line-height: 1;
font-size: 40px;
color: $brand-primary;

    }
    ...
```

Sorting vanilla CSS:

``` css
.test {
    color: #000;
    font-size: 12px;
    height: 100px;
    width: 100px;
}
```

![st3-csscomb-error](https://cloud.githubusercontent.com/assets/3292452/3669047/b194b608-122b-11e4-8e30-9347bc257de8.png)
