### ISSUE TITLE
Throws exception if extended class contains "-" in its name (SCSS)

### ISSUE THREAD

**Issue by sh-a-a** [csscomb/sublime-csscomb#36]
``` css
.paper
{
    @extend .row;
    @extend .small-12;
    position: relative;
   //...
}
```

will cause:

```
core.js:412
            throw e;
                  ^

Please check the validity of the block starting from line #848
846 | {
847 |     @extend .row;
848*|     @extend .small-12;
```
