### ISSUE TITLE
Enforce /n between declarations

### ISSUE THREAD

**Issue by jb510** [csscomb/sublime-csscomb#48]
I can't seem to figure out how to force a new line between declarations.

given this CSS two declaration groups on a single line

``` css
.page_caption h1,.page_caption h2.heading {margin-bottom: 15px;margin-left: 0;font-size: 33px;}.page_caption p {font-size: 20px;}
```

I expected

``` css
.page_caption h1,
.page_caption h2.heading {
    margin-bottom: 15px;
    margin-left: 0;
    font-size: 33px;
}
.page_caption p {
    font-size: 20px;
}
```

but I get this

``` css
.page_caption h1,
.page_caption h2.heading {
    margin-bottom: 15px;
    margin-left: 0;
    font-size: 33px;
}.page_caption p {
    font-size: 20px;
}
```

my rule set is

```
   "config": {
    "always-semicolon": true,
    "color-case": "lower",
    "block-indent": "\t",
    "color-shorthand": true,
    "element-case": "lower",
    "eof-newline": false,
    "leading-zero": false,
    "quotes": "double",
    "space-before-colon": "",
    "space-after-colon": " ",
    "space-before-combinator": "",
    "space-after-combinator": "",
    "space-between-declarations": "\n\n\n",
    "space-before-opening-brace": " ",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": "\n",
    "space-before-selector-delimiter": "",
    "space-before-closing-brace": "\n",
    "strip-spaces": true,
    "unitless-zero": true,
    "vendor-prefix-align": true
}
```

Is this a bug, missing feature, by design?
