### ISSUE TITLE
Issues with .scss

### ISSUE THREAD

**Issue by gpolguere** [csscomb/sublime-csscomb#57]
From this .scss :

``` scss
#test
{
    background-image: url($path-img + 'img/static/mobile/common-bg.jpg');
}
```

I got this as result :

``` scss
#test
{
    background-image: url($path-img ) 'img/static/mobile/common-bg.jpg';;
}
```

The '+' sign is changed into '(' and ')' into ';'.
